# -*- coding: utf-8 -*-
# Generated by Pony ORM 0.8-dev on 2017-01-27 16:44
from __future__ import unicode_literals

from pony import orm

dependencies = []

def define_entities(db):
    class StoredItem(db.Entity):
        description = orm.Optional(str)
    
    
    class Video(db.StoredItem):
        duration_sec = orm.Optional(int)
    
    
    class Text(db.StoredItem):
        contents = orm.Required(str)
    
    
    class Picture(db.StoredItem):
        width = orm.Optional(int)
        height = orm.Optional(int)
        f = orm.Optional(str)
