# -*- coding: utf-8 -*-
# Generated by Pony ORM 0.8-dev on 2017-01-27 16:44
from __future__ import unicode_literals

from pony import orm
from pony.migrate import diagram_ops as op

dependencies = [u'0001_initial']

operations = [
    op.AddAttr(b'StoredItem', b'url', orm.Required(str, initial='')),
]
