# -*- coding: utf-8 -*-
# Generated by Pony ORM 0.8-dev on 2017-01-30 12:58
from __future__ import unicode_literals

from pony.migrate import diagram_ops as op
from pony.orm import *

dependencies = [u'0003_20170127_1644']



def forward(db):
    text1 = db.Text(contents='text1', url='/text1')
    text2 = db.Text(contents='text2', url='/text2')
    text3 = db.Text(contents='text3', url='/text3')
    text1.comments = [text2, text3]

operations = [
    op.Custom(forward=forward)
]

