# -*- coding: utf-8 -*-
# Generated by Pony ORM 0.6.7-dev on 2016-10-08 18:49
from __future__ import unicode_literals

from pony import orm

dependencies = []

db = orm.Database('mysql', db='testdb', host='localhost', passwd='ponytest', user='ponytest')

class T1(db.Entity):
    peers = orm.Set('T2')
    n = orm.Required(int)

class T2(db.Entity):
    peers = orm.Set('T1')
