# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests-and-lint

on:
  push:
    branches: [ github-actions ]
  pull_request:
    branches: [ github-actions ]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pylint
          if [ -f pony/orm/tests/requirements.txt ]; then pip install -r pony/orm/tests/requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 pony --count --exit-zero --exclude tests,examples,flask,thirdparty  --max-complexity=10 --max-line-length=127 --statistics
      - name: Lint with pylint
        run:
          pylint --ignore tests,examples,flask,thirdparty --exit-zero --max-line-length=127 --confidence INFERENCE --jobs 2 pony/

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.9]
        # database: [mysql, oracle, postgres, sqlite, cockroach]
        database: [sqlite, postgres]
        # architecture: [x64]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: pony
          POSTGRES_USER: pony
          POSTGRES_PASSWORD: pony
          POSTGRES_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install coverage
        if [ -f pony/orm/tests/requirements.txt ]; then pip install -r pony/orm/tests/requirements.txt; fi
    - name: Test with coverage
      env:
        pony_test_db: $(pwd)/pony/orm/tests/dbconf/${{ matrix.database }}
      run: |
        # Setup database
        echo $pony_test_db
        export pony_test_db=$(pwd)/pony/orm/tests/dbconf/${{ matrix.database }} && echo $pony_test_db
        echo $pony_test_db
        # run unittest
        coverage run --source pony.orm.dbapiprovider,pony.orm.dbschema,pony.orm.decompiling,pony.orm.core,pony.orm.sqlbuilding,pony.orm.sqltranslation --branch -m unittest discover
        # coverage run -a --source pony.orm.dbapiprovider,pony.orm.dbschema,pony.orm.decompiling,pony.orm.core,pony.orm.sqlbuilding,pony.orm.sqltranslation --branch pony/orm/tests/sql_tests.py

        coverage html -i
        coverage xml -i
        coverage report -i

